### ISSUE TITLE
slick slide修整

### ISSUE THREAD

**Issue by aharu6** [akiray3/r-jp-doc#12]
homeのslickslideがお試しで作った内容になっているので、直す。

**Comment by aharu6** [comment]
スライド数が多すぎるのか、再読み込みした時にスライドの形が崩れる。
画像があるものだけに絞るか。

**Comment by akiray3** [comment]
> スライド数が多すぎるのか、再読み込みした時にスライドの形が崩れる。
> 画像があるものだけに絞るか。

修整できそう？

**Comment by aharu6** [comment]
> 修整できそう？

出来そうです

**Comment by aharu6** [comment]
base, graphics, psych,stats全てまとめてスライドを書き出そうとしていたのが良くなかった。
それぞれ分けて解決。
