### ISSUE TITLE
画面レイアウト

### ISSUE THREAD

**Issue by aharu6** [akiray3/r-jp-doc#25]
モバイル、PCでの表示を分ける。

- [x] 押したタブ名にアンダーバーをつけて見やすくする
- [x] 説明がないタフは非表示に
- [x] レスポンシブなフォントサイズ
- [x] base一覧の絞り込みボタン修正
- [x] ページトップに戻るボタン　(関数一覧のページ）
- [x] 整頓(javascriptで全部生成していたものをhtmlとcssに引っ越し　ファイルの構造が変わったことに伴う変更。）
- [x] モバイル用の関数一覧ページを直す
- [x] graphics用のイラスト増やす

**Comment by akiray3** [comment]
*ここではないかも

このhtmlのままの文字列、こちらで地のテキストに変換しておいたほうが良いかな？
htmlのタグをそのまま表示時に反映させられれば、見栄え良いかなって残しておいたんだけど。

![image](https://github.com/akiray3/r-jp-doc/assets/129808898/54f0ef1a-7e12-409d-a24e-4a989ae3e284)

**Comment by aharu6** [comment]
反映してみます。見やすいほうがいいですよね
ここにスクショはっておきます

**Comment by aharu6** [comment]
![Uploading イメージ.png…]()

**Comment by akiray3** [comment]
モバイル版とPC版をレスポンシブコーディングで、別々に定義しておき、使用端末によって異なる変数が適用されるように修正してみたいと思います。
いまのところPC表示では横スクロールが発生していますね。
見栄えを整えるのは機能全体が固まってもいいかもしれないので、これは将来的な仕様変更です。
