### ISSUE TITLE
修整

### ISSUE THREAD

**Issue by aharu6** [akiray3/r-jp-doc#28]
mergeしてもらった後の動作確認。
おかしな所を書き出していく。

- [x] - baseの一覧に飛ぶリンク
- [x] - 関数のページの表示

**Comment by aharu6** [comment]
- 検索ボックスの虫眼鏡アイコンが行方不明

**Comment by akiray3** [comment]
あ！ごめんそれ間違えて消してしまったかも！
一回Merge前に戻してみようか。

**Comment by akiray3** [comment]
大変失礼しました。
今回Mergeがあんまり上手くいっていないのかも。
help_db_jpn_main.jsonがコンフリクトしてたのを直したくらいなんだけど。

**Comment by aharu6** [comment]
アイコンわかるので大丈夫です。
機能面では、データベースを更新して貰っているので、それにJavaScriptが対応できていないのが原因かな。と思ってます。
今晩修整してみます

**Comment by aharu6** [comment]
諸々動くようになりました。お騒がせしました。

**Comment by akiray3** [comment]
データベースの列構造を、こちらで勝手に変えてしまったので、動かなくなったのですね！
今後は事前にわかるようにします！

**Comment by aharu6** [comment]
こちらが対応しきれていなかっただけなのでお気になさらず。
データベースありがとうございます。
