### ISSUE TITLE
GithubでMergeできない

### ISSUE THREAD

**Issue by akiray3** [akiray3/r-jp-doc#6]
![image](https://github.com/akiray3/r-jp-doc/assets/129808898/de12c7d4-d308-4932-b59c-df0ec0799648)

最初から別々に作ってしまったので、Mergeできないらしい。
"creage-page"の中身をすべて手動で"main"にコピーして、create-pageブランチは削除してもいいでしょうか。

**Comment by aharu6** [comment]
了解です。お願いします。しばらくストップします。
お手数おかけします。

**Comment by akiray3** [comment]
> 了解です。お願いします。しばらくストップします。
> お手数おかけします。

OK。ゆっくりやりましょう。
