### ISSUE TITLE
各関数ごとの切り替え

### ISSUE THREAD

**Issue by aharu6** [akiray3/r-jp-doc#9]
まずは関数紹介ページで全て「function」になっている表示を関数ごとに切り替えるようにしてみる。
jsonファイルの読み込み。

ホームのslickslideの内容も、関数紹介も、全部まとめて切り替えられるようにできたら良いけど、進みが亀なので細分化。

**Comment by akiray3** [comment]
> jsonファイルの読み込み。

けっこう大きなデータになってしまったので、読み込みに時間がかかるかもしれない。
ひとまず基本的な方法で読み込みを試してもらって、あまりにモッサリする場合はfirebaseというgoogleのデータベースを利用したほうがいいかも。予備案。
